In [2]:
import numpy as np

def sprl_mtrx(J,v=[]):
    
    # Returns a list of spiral entries from a matrix

    M = J.copy()

    if M.ndim<=1 or M.shape[0]==1:

        for m in M:

            for n in m:

                 v.append(m)

    elif M.shape[1]==1:

        for i in M:

            for j in i:

                v.append(j)

    else:

        for m in M[0]:

            v.append(m)

        M = np.rot90(M[1:,])

        sprl_mtrx(M,v)

    return v

In [3]:
A = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14],[15,16,17,18,19,20,21],[22,23,24,25,26,27,28]])

In [4]:
print('Matrix: ',A)

Matrix:  [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]]


In [5]:
spiral = sprl_mtrx(A)

In [6]:
print('Spiral: ',spiral)

Spiral:  [1, 2, 3, 4, 5, 6, 7, 14, 21, 28, 27, 26, 25, 24, 23, 22, 15, 8, 9, 10, 11, 12, 13, 20, 19, 18, 17, 16]
